<?php

return [
    'Drarga-agadir',
    'Tikiouine',
    'Dcheira',
    'Ait melloul',
    'Taddart - agadir',
    'Belfaa',
    'Inezgane',
    'Temsia',
    'Taghazoute',
    'Sidi bibi',
    'Biougra',
    'Tamraght',
    'Tiznit',
    'Lqliaa',
    'Anza',
    'Ait amira',
    'Ouled dahhou',
    'Massa',
    'Azrou-agadir',
    'Awrir-agadir',
    'Agadir',
    'Demnate',
    'Tamallalt',
    'Laattaouia',
    'Kelaa de sraghna',
    'Sidi bou othmane',
    'Nzalate laadim',
    'Rehamna',
    'Ben guerir',
    'Aghbalou',
    'Ouzoud',
    'Aghbala',
    'Ouled mbarek',
    'Souk sebt',
    'Ouled zmam',
    'Ait ishak',
    'Tighessaline',
    'Ouled youssef',
    'Zawiat cheikh',
    'Aguelmouss -khenifra',
    'Afourer',
    'Mrirt',
    'Beni mellal',
    'Ouled yaiche',
    'Sidi jaber',
    'Souq sebt oled nema',
    'El ksiba',
    'Fkih ben salah',
    'Kasba tadla',
    'Dar ould zidouh',
    'Oulad ayad',
    'Had elbradia',
    'Khenifra',
    'Azilal',
    'Ben ahmed',
    'El gara',
    'Sidi hajjaj',
    'El borouj',
    'Berrechid',
    'Derouat',
    'Settat',
    'Nouaceur',
    'Mediouna',
    'Bouskoura',
    'Casablanca',
    'Sidi mokhtar',
    'Chichaoua',
    'Imintanoute',
    'Dakhla',
    'Tnine chtouka',
    'Jorf lasfar',
    'Zawyat sidi ismail',
    'Ouled frej',
    'Ghadbane',
    'Bir jdid',
    'Sidi bennour',
    'Sidi abed',
    'Moulay abdellah',
    'Khamis zemamra',
    'El jadida',
    'Sidi bouzid',
    'Azemmour',
    'Arfoud',
    'Tinejdad',
    'Rissani',
    'Goulmima',
    'Errachidia',
    'Sidi harazem',
    'Ain chkef',
    'Moulay yacoub',
    'Oulad tayeb',
    'Ain cheggag',
    'Imouzzer kandar',
    'Sefrou',
    'Fes',
    'Sidi slimane',
    'Khenichet',
    'Souk larbaa du gharb',
    'Mechra bel ksiri',
    'Jorf el melha',
    'Sidi-kacem',
    'Errahma',
    'Tamaris',
    'Sidi rahhal',
    'Dar bouazza',
    'Had soualem',
    'Oulad berhil',
    'Taliouine',
    'Assaki',
    'Sebt el guerdane',
    'Ait iaaza',
    'Aoulouz',
    'taroudant',
    'Oulad teima',
    'Howara',
    'Kenitra',
    'Sidi yahya el gharb',
    'Sidi taibi',
    'Ouazzane',
    'Moulay bouselham',
    'Zoumi',
    'Lalla mimouna',
    'Tanger',
    'Ksar sghir',
    'Larache',
    'Ksar el kebir',
    'Assilah',
    'Gzenaya',
    'Tleta loulad',
    'Khouribga',
    'Oued zem',
    'Boujniba',
    'Bejaad',
    'Laayoune',
    'Essemara',
    'Boujdour',
    'Foum el oued',
    'Tarfaya',
    'Laayoune port',
    'Tan tan',
    'El ouatia',
    'Guelmim',
    'Sidi ifni',
    'Bouizakarne',
    'Assa',
    'Assa zag',
    'Marrakech',
    'Tamensourt',
    'Tahanaoute',
    'Tameslouhte',
    'Ait ourir - marrakech',
    'Loudaya',
    'Ourika',
    'Chouiter',
    'Meknes',
    'Boufakrane',
    'El haj kaddour',
    'Sbaa aiyoun',
    'Ain taoujdate',
    'Azrou',
    'El hajeb',
    'Tifelt',
    'Khemisset',
    'M\'haya',
    'Moulay driss zerhoun',
    'Ifrane',
    'Ain jemaa',
    'Agourai',
    'Boulemane',
    'Outat el haj',
    'Missour',
    'Boumia',
    'Zaida',
    'Er-rich',
    'Midelt',
    'Sidi hajjaj tit mlil',
    'El mansouria',
    'Tit mellil',
    'Bouznika',
    'Benslimane',
    'Ain harrouda',
    'Mohammedia',
    'Al aaroui',
    'Bni ansar',
    'Nador',
    'Selouane',
    'Zaio - nador',
    'Zeghanghane',
    'Driouch',
    'Farkhana',
    'Beni chiker',
    'Kariat arkmane',
    'Tiztoutine',
    'Midar',
    'Rabat',
    'Tetouan',
    'Martil',
    'Fnidq',
    'Mdiq',
    'Chefchaouen',
    'Bab taza',
    'Oued laou',
    'Bab berred',
    'Temara',
    'Harhoura',
    'Skhirate',
    'Ain attig',
    'Ain el aouda',
    'Tamesna',
    'Tahla',
    'Guercif',
    'Oued amlil',
    'Taza',
    'Taourirt',
    'Taounate',
    'Tissa-taounate',
    'Ain aicha',
    'Karia ba mohamed',
    'Khlalfa',
    'Ghafsai',
    'Ouarzazate',
    'Kalaat mgouna',
    'Ighrem nougdal',
    'Skoura ouarzazat',
    'Agdz',
    'Zagora',
    'Taznakht',
    'Aguelmouss-ouarzazate',
    'Tinghir',
    'Boumalne dades',
    'Alnif',
    'Sale',
    'Sala al jadida',
    'Bouknadel',
    'Safi',
    'Jamaat shaim',
    'Sebt gzoula',
    'Youssoufia',
    'Chemmaia',
    'Essaouira',
    'Oualidia',
    'Tleta sidi bouguedra',
    'El ghazoua',
    'Figuig',
    'Ajdir',
    'Bni bouayach',
    'Imzouren',
    'Al hoceima',
    'Bouarfa',
    'Aklim',
    'Ain bni mathar',
    'Bni drar',
    'Jerada',
    'Laayoune oriental',
    'Ras el ma',
    'Ahfir',
    'Saidia',
    'Berkane',
    'Oujda',
    'Sidi allal el bahraoui',
    'Tata',
    'Laaouamera',
    'issaguen',
    'Merzouga',
    'Mirleft',
    'Amizmiz',
    'Arbaa aounate',
    'Sidi yahya zair',
    'Souiria',
    'Marrakech-oya',
    'Akka',
    'Sidi rahhal chaouia',
    'Ait ishaq',
    'Sidi allal tazi',
    'Boudnib',
    'Tendrara - oujda',
    'Bin el widan',
    'Foum zguid',
    'Akhfennir',
    'Targuist',
    'Bhalil',
    'Beni ayat',
    'Ouaouizarht',
    'Tamanar',
    'Stehat',
    'Bouderbala',
    'Sidi ishaq',
    'Ben taib',
    'Ben taieb - nador',
    'Zawiat sidi ismail',
    'Oulad moussa',
    'Arbaoua',
    'igherm taroudant',
    'Tafraoute',
    'madagh',
    'delalha',
    'Bouanane',
    'oulad said alouad',
    'sebaa ayoun',
    'Ribate el khier',
    'Tamsaman',
    'Ait baha',
    'Mhamid ghizlane',
    'Itzer',
    'Aknoul - taza',
    'sidi moussa',
    'Beni drar',
    'Rommani',
    'Ain dorij bmd',
    'sidi redouane',
    'Dar gueddari',
    'Tassoultante',
    'Asni',
    'Oulmes',
    'Skhour rehamna',
    'Guisser',
    'Ouled amrane',
    'Moulay Bouazza',
    'Had harara',
    'Had kourt',
    'Souk sabt oulad nema',
    'Oulad aissa beni melal',
    'Fquih ben salah',
    'Had bradia',
    'Khemis sahel',
    'Imi ouaddar',
    'Souihla',
    'Timahdite',
    'Teroual',
    'Ouled abou',
    'Tanant',
    'Ouaoumana',
    'Smimou',
    'Tafarist',
    'sidi ghanem',
    'khmis mdiq',
    'Maaziz',
    'Mehaya',
    'Tounfite',
    'Ain leuh',
    'imouzzer marmoucha',
    'Mernissa - Taounate',
    'Lakhssas',
    'Ain Mediouna - Taounate',
    'El Menzel',
    'Ait Kamra',
    'Agouim-Ouarzazate',
    'Sidi Taibi - Kenitra',
];
